services:
  - type: web
    name: trip-planner-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app/backend/app.py
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
